#!/bin/bash

BREAKS=(-61 9 38 199 426 686 756 818 1111 1181 1210 1635 2060 2097 2192 2262 2324 2394 2456 3178)

exit_error() {
  >&2 echo "$1"
  exit 1
}

to_jalaali() {
  local gy=$1
  local gm=$2
  local gd=$3

  echo $(d2j $(g2d $gy $gm $gd))
}

g2d() {
  local gy=$1
  local gm=$2
  local gd=$3
  local d=$(( (gy + (gm - 8) / 6 + 100100) * 1461 / 4 + (153 * ((gm + 9) % 12) + 2) / 5 + gd - 34840408 ))

  echo $(( d - ((gy + 100100 + (gm - 8) / 6) / 100) * 3 / 4 + 752 ))
}

d2g() {
  local jdn=$1
  local j=$((4 * jdn + 139361631))
  j=$(( j + (3 * ((4 * jdn + 183187720) / 146097) / 4) * 4 - 3908 ))
  local i=$(( ((j % 1461) / 4) * 5 + 308 ))
  local gd=$(( ((i % 153) / 5) + 1 ))
  local gm=$(( (i / 153) % 12 + 1 ))
  local gy=$(( j / 1461 - 100100 + (8 - gm) / 6 ))

  echo "$gy $gm $gd"
}

jal_cal() {
  local jy=$1
  local without_leap=$2
  local bl=${#BREAKS[@]}
  local gy=$((jy + 621))
  local leapj=-14
  local jp=${BREAKS[0]}

  if [[ $jy -lt $jp || $jy -ge ${BREAKS[$((bl - 1))]} ]]; then
    exit_error "Invalid Jalaali year $jy"
  fi

  for ((i = 1; i < bl; i++)); do
    local jm=${BREAKS[$i]}
    local jump=$((jm - jp))

    if [[ $jy -lt $jm ]]; then
      break
    fi

    leapj=$(( leapj + (jump / 33) * 8 + (jump % 33) / 4  ))
    jp=$jm
  done

  local n=$((jy - jp))
  leapj=$(( leapj + (n / 33) * 8 + ((n % 33) + 3) / 4 ))

  if [[ $((jump % 33)) -eq 4 && $((jump - n)) -eq 4 ]]; then
    leapj=$((leapj + 1))
  fi

  leapg=$(( gy / 4 - ((gy / 100) + 1) * 3 / 4 - 150 ))
  march=$((20 + leapj - leapg))

  if [[ $without_leap == "false" ]]; then
    if [[ $((jump - n)) -lt 6 ]]; then
      n=$(( n - jump + ((jump + 4) / 33) * 33 ))
    fi

    local leap=$(( ((n + 1) % 33 - 1) % 4 ))

    if [[ leap -eq -1 ]]; then
      leap=4
    fi
  fi

  echo "$leap $gy $march"
}

d2j() {
  local jdn=$1
  local gy=$(d2g $jdn)
  gy=${gy%% *}
  local jy=$((gy - 621))
  local r="$(jal_cal $jy 'false')"
  local jdn1f=$(g2d $gy 3 ${r##* })
  local k=$((jdn - jdn1f))

  if [[ $k -ge 0 ]]; then
    if [[ $k -le 185 ]]; then
      local jm=$((1 + k / 31))
      local jd=$((k % 31 + 1))
      echo "$jy-$jm-$jd"
      return 0
    else
      k=$((k - 186))
    fi
  else
    jy=$((jy - 1))
    k=$((k + 179))

    if [[ ${r%% *} -eq 1 ]]; then
      k=$((k + 1))
    fi
  fi

  local jm=$((7 + k / 30))
  local jd=$((k % 30 + 1))

  echo "$jy-$jm-$jd"
}

read input_date

y=${input_date%%-*}
m=${input_date%-*}
m=${m#*-}
d=${input_date##*-}

to_jalaali $y $m $d
